spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PG_URL:localhost}:${DB_PG_PORT:5432}/ihne?sslmode=require
    username: ${DB_PG_USER:root}
    password: ${DB_PG_PASS:pw}
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000 #1 min
      validation-timeout: 1000 #1 sec
      idle-timeout: 300000 #5 mins
      minimum-idle: 2
      maximum-pool-size: 5
      max-lifetime: 600000 #10 mins
