spring.config.activate.on-profile: "postgres"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:ihne}
    username: ${DB_USER:root}
    password: ${DB_PASS:pw}
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000 #1 min
      validation-timeout: 1000 #1 sec
      idle-timeout: 300000 #5 mins
      minimum-idle: 2
      maximum-pool-size: 5
      max-lifetime: 600000 #10 mins
      connection-init-sql: "CREATE TABLE IF NOT EXISTS shedlock(name VARCHAR(64) NOT NULL, lock_until TIMESTAMP NOT NULL,
        locked_at TIMESTAMP NOT NULL, locked_by VARCHAR(255) NOT NULL, PRIMARY KEY (name));"
