spring:
  profiles:
    active: local
    group:
      "prod": "${DB_PROFILE:mysql},shedlock"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    reactive:
      max-chunk-size: 8192
